[debug] [2019-04-29T10:45:58.178Z] ----------------------------------------------------------------------
[debug] [2019-04-29T10:45:58.186Z] Command:       /usr/bin/node /usr/local/bin/firebase serve
[debug] [2019-04-29T10:45:58.187Z] CLI Version:   6.7.1
[debug] [2019-04-29T10:45:58.187Z] Platform:      linux
[debug] [2019-04-29T10:45:58.188Z] Node Version:  v8.10.0
[debug] [2019-04-29T10:45:58.188Z] Time:          Mon Apr 29 2019 13:45:58 GMT+0300 (EAT)
[debug] [2019-04-29T10:45:58.188Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-04-29T10:45:58.369Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-04-29T10:45:58.370Z] > authorizing via signed-in user
[debug] [2019-04-29T10:45:58.370Z] [iam] checking project payments-1fe5e for permissions ["firebase.projects.get"]
[debug] [2019-04-29T10:45:58.377Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2019-04-29T10:45:58.378Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2019-04-29T10:45:59.805Z] <<< HTTP RESPONSE 200
[debug] [2019-04-29T10:45:59.859Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/payments-1fe5e:testIamPermissions  

[debug] [2019-04-29T10:46:02.138Z] <<< HTTP RESPONSE 200
[debug] [2019-04-29T10:46:02.143Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/payments-1fe5e  
 
[debug] [2019-04-29T10:46:04.316Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/home/licio/Documents/Payments2'...
[info] 
[debug] [2019-04-29T10:46:12.659Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:102:23)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:23
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:13:26)
    at Command.module.exports.Command.description.option.option.option.option.before.action [as _action] (/usr/local/lib/node_modules/firebase-tools/lib/commands/serve.js:55:12)
[error] 
[error] Error: An unexpected error has occurred.
